django/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('simulate/', views.simulate, name='simulate'),
]

django/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

django/main/models.py
from django.db import models

# Create your models here.

django/main/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse # 불필요

def index(request):
    if request.method == 'POST':
        return render(request, 'main/index.html',{'trs':range(9), 'tds':range(9)})
    else:
        return render(request, 'main/index.html',{'trs':range(9), 'tds':range(9)})

def simulate(request):
    return render(request, 'main/simulate.html')

django/main/templates/main/TrafficIntegrationSystemRendering.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Traffic Integration System</title>
    <canvas id = "ShowSimulationCanvas"></canvas>
    <canvas id = "ShowTrafficLightStateCanvas"></canvas>
    <canvas id = "ConvertTrafficLightStateCanvas"></canvas>
    <script src = "TrafficPoint.js"></script>
    <script src = "TrafficLight.js"></script>
    <script src = "TrafficCar.js"></script>
    <script src = "Canvas.js"></script>
    <script>
        function drawRect(ctx, x, y, width, height, color) {
            ctx.fillStyle = color;
            ctx.fillRect(x, y, width, height);
        }

        function drawCircle(ctx, point, color) {
            ctx.beginPath();
            ctx.arc(
                point.x, point.y, 5,
                0, Math.PI * 2,
                true
            );
            ctx.closePath();
            ctx.fillStyle = color;
            ctx.fill();
        }

        function movePoint(ctx, movePoint, rotatePoint) {
            console.log(movePoint.x, movePoint.y);

            if(movePoint.x < 200) {
                movePoint.addNowPosition(1, 0);
            } else {
                if(movePoint.y > 200) {
                    movePoint.rotatePosition(rotatePoint, -Math.PI / 24);
                } else {
                    movePoint.addNowPosition(0, -1);
                }
            }
            
            drawCircle(ctx, movePoint, "rgb(255, 0, 0)");
        }

        var point             = new TrafficPoint(0, 250);
        var rotate            = new TrafficPoint(200, 200);
        var simulationCanvas  = new Canvas("ShowSimulationCanvas", 500, 500, "rgb(255, 250, 250)", true, "rgb(100, 100, 100)");

        drawRect(simulationCanvas.canvasContext, 0, 0, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 300, 0, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 0, 300, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 300, 300, 200, 200, "rgb(200, 200, 200)");
            
        drawCircle(simulationCanvas.canvasContext, point, "rgb(255, 0, 0)");

        var init = function() {
            movePoint(simulationCanvas.canvasContext, point, rotate);
        };
        
        setInterval(
            init,
            100
        );


    </script>
</head>
<body>
</body>
</html>

django/main/templates/main/caculateModal.html
{# line-show와 연결된 모달이 여러 개면 id만 바꿔가며 이걸 여러 개 넣는다 #}
{# 1. 등록 #}
<div class="modal fade" id="caculateModal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            {# 헤더 - 제목만 바꾼다 #}
            <div class="modal-header">
                <h5 class="modal-title" id="modal">시뮬레이션 설정</h5>
                {# 제목 옆 X 버튼이다 #}
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            {# 바디 #}
            <div class="modal-body">
                <form>

                    {# 각 묶음이 1 줄을 차지한다. 적당한 것을 조합 해 여러 줄을 만들면 된다. #}
                    {# 맨 마지막 줄에 푸터 있다. 넣는거 빼먹지 마라. #}
                    
                    {# 행을 나누는 경우(2분할) - textarea #}
                    <div class="form-row">
                        {# 행은 전체 12행이므로, 6은 절반을 차지하겠다는 의미이다. #}
                        <div class="form-group col-sm-6">
                            <label>x좌표</label>
                            <input type="text" name="matrix1" id="matrix1" class="form-control" maxlength="20">
                        </div>
                        <div class="form-group col-sm-6">
                            <label>y좌표</label>
                            <input type="text" name="matrix2" id="matrix2" class="form-control" maxlength="20">
                        </div>
                    </div>
                    
                    {# 푸터 #}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                        <!--<button type="submit" class="btn btn-primary">계산</button>-->
                        <button onclick="caculate()" type="button" class="btn btn-primary">계산</button>
                    </div>
                </form>
            </div>
        </div> 
    </div>
</div>


<script>
    function caculate() {
        var xx = document.querySelector("#matrix1").value;
        var yy = document.querySelector("#matrix2").value;

        var right = xx * 2;
        var down = yy * 2;

        alert("오른쪽으로: " + right);
        alert("아래쪽으로: " + down);
    }
</script>

django/main/templates/main/card.html
<div class="card bg-light bg-light mt-3">
    <div class="card-header bg-light">
        <div class="row">
            <div class="col-8 text-left">긴급차량 우선 교통 시스템</div>
        </div>
    </div>
    <div class="card-body">
        <h5 class="card-title">
            시뮬레이션
        </h5>
        <p class="card-text">
            <button class="btn btn-primary mx-1 mt-2" data-toggle="modal" href="#simulationModal">시뮬레이션</button>
            <br>
            <button class="btn btn-primary mx-1 mt-2" data-toggle="modal" href="#caculateModal">최단거리 계산</button>
        </p>
    </div>
</div>

django/main/templates/main/index.html
{% extends "main/navbar.html" %}
{% load static %}

{% block title %}TIS{% endblock %}

{% block body %}
<section class="container">
    {% include "main/simulationModal.html" %}
    {% include "main/caculateModal.html" %}
    {% include "main/card.html" %}
    <style>
        .rows {
            display: flex;
        }
        .cols {
            width: 100px;
            height: 100px;
        }

        .game-board {
            width: 900px;
            margin: 0 auto;
        }
        .rows {
            display: flex;
        }
        .cols {
            width: 100px;
            height: 100px;
        }
        .cols:nth-child(odd) {
            background-color:gray;
        }
        .rows:nth-child(odd) {
            background-color:gray;
        }
        .cols:hover {
            background-color:#2574D0;
        }
    </style>
    
    <div class="game-board">
        {% for tr in trs %}
        
        <div class="rows">
            {% for td in tds %}
            <div class="cols">
                <span></span>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

django/main/templates/main/navbar.html
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta charset="UTF-8">
        <!-- CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'cssjs/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'cssjs/owl.carousel.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'cssjs/owl.theme.default.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'cssjs/custom.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css">
        {% block head %}{% endblock %}
    </head>
    <body>
    <!-- style="background-color:#A41034;
        <nav class="navbar fixed-bottom bg-primary navbar-dark nav-tp navbar-expand py-0 shadow-lg-bottom" id="navbar_top"> 
            <div class="collapse navbar-collapse" id="inside">
                <ul class="navbar-nav mx-auto isl" id="nav">
                    <li class="nav-item mx-2 my-auto active">
                        <a class="nav-link px-2 py-1 text-center" href="">
                            <i class="fab fa-kickstarter pt-1" style="font-size:1.8em;"></i>
                            <p class="nav-link my-0 px-0 pt-1 pb-0" href="">navbar</p>
                        </a>
                    </li>
                    <li class="nav-item mx-2 my-auto">
                        <a class="nav-link px-2 py-1 text-center" href="">
                            <i class="fas fa-comments pt-1" style="font-size:1.8em;"></i>
                            <p class="nav-link my-0 px-0 pt-1 pb-0" href="">테스트</p>
                        </a>
                    </li>
                    <li class="nav-item mx-2 my-auto">
                        <a class="nav-link px-2 py-1 text-center" href="">
                            <i class="fas fa-book pt-1" style="font-size:1.8em;"></i>
                            <p class="nav-link my-0 px-0 pt-1 pb-0" href="">navbar</p>
                        </a>
                    </li>
                    <li class="nav-item mx-2 my-auto">
                        <a class="nav-link px-2 py-1 text-center" href="">
                            <i class="fas fa-user-circle pt-1" style="font-size:1.8em;"></i>
                            <p class="nav-link my-0 px-0 pt-1 pb-0" href="">test</p>
                        </a>
                    </li>
                </ul>
            </div>
            <style>
                .nav-link {
                    font-size: 10pt;
                }
            </style>
        </nav>
    -->

        {% block body %}{% endblock %}

        <footer class="bg-dark mt-5 p-4 text-center" style="color:#ffffff;">
            TIS (Traffic Integration System)<br>
            광운대학교 삐뽀삐뽀팀 개발
        </footer>

        <!-- JS -->
        <script type="text/javascript" src="{% static 'cssjs/jquery.min.js' %}"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'cssjs/owl.carousel.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'cssjs/custom.js' %}"></script>
    </body>
</html>

django/main/templates/main/simulate.html
{% extends "main/navbar.html" %}
{% load static %}

{% block title %}시뮬레이션{% endblock %}

{% block head %}
    <!-- Custom JS-->
    <script type="text/javascript" src="{% static 'Canvas.js' %}"></script>
    <script type="text/javascript" src="{% static 'TrafficCar.js' %}"></script>
    <script type="text/javascript" src="{% static 'TrafficLight.js' %}"></script>
    <script type="text/javascript" src="{% static 'TrafficPoint.js' %}"></script>

    <div class="container text-center">
    <canvas id = "ShowSimulationCanvas"></canvas>
    <canvas id = "ShowTrafficLightStateCanvas"></canvas>
    <canvas id = "ConvertTrafficLightStateCanvas"></canvas>
    </div>
    <script>
        function drawRect(ctx, x, y, width, height, color) {
            ctx.fillStyle = color;
            ctx.fillRect(x, y, width, height);
        }

        function drawCircle(ctx, point, color) {
            ctx.beginPath();
            ctx.arc(
                point.x, point.y, 5,
                0, Math.PI * 2,
                true
            );
            ctx.closePath();
            ctx.fillStyle = color;
            ctx.fill();
        }
        
        function movePoint(ctx, movePoint, rotatePoint) {
            console.log(movePoint.x, movePoint.y);

            if(movePoint.x < 200) {
                movePoint.addNowPosition(1, 0);
            } else {
                if(movePoint.y > 200) {
                    movePoint.rotatePosition(rotatePoint, -Math.PI / 24);
                } else {
                    movePoint.addNowPosition(0, -1);
                }
            }
            
            drawCircle(ctx, movePoint, "rgb(255, 0, 0)");
        }

        var point             = new TrafficPoint(0, 250);
        var rotate            = new TrafficPoint(200, 200);
        var simulationCanvas  = new Canvas("ShowSimulationCanvas", 500, 500, "rgb(255, 250, 250)", true, "rgb(100, 100, 100)");

        drawRect(simulationCanvas.canvasContext, 0, 0, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 300, 0, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 0, 300, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 300, 300, 200, 200, "rgb(200, 200, 200)");
            
        drawCircle(simulationCanvas.canvasContext, point, "rgb(255, 0, 0)");

        var init = function() {
            movePoint(simulationCanvas.canvasContext, point, rotate);
        };
        
        setInterval(
            init,
            100
        );
    </script>
{% endblock %}

{% block body %}
{% endblock %}

django/main/templates/main/simulationModal.html
{# line-show와 연결된 모달이 여러 개면 id만 바꿔가며 이걸 여러 개 넣는다 #}
{# 1. 등록 #}
<div class="modal fade" id="simulationModal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            {# 헤더 - 제목만 바꾼다 #}
            <div class="modal-header">
                <h5 class="modal-title" id="modal">시뮬레이션 설정</h5>
                {# 제목 옆 X 버튼이다 #}
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            {# 바디 #}
            <div class="modal-body">
                <form action="{% url 'main:simulate' %}" method="POST">{%csrf_token%}

                    {# 각 묶음이 1 줄을 차지한다. 적당한 것을 조합 해 여러 줄을 만들면 된다. #}
                    {# 맨 마지막 줄에 푸터 있다. 넣는거 빼먹지 마라. #}
                    
                    {# 행을 나누는 경우(2분할) - textarea #}
                    <div class="form-row">
                        {# 행은 전체 12행이므로, 6은 절반을 차지하겠다는 의미이다. #}
                        <div class="form-group col-sm-6">
                            <label>사고 지점 x좌표</label>
                            <input type="text" name="matrix1" class="form-control" maxlength="20">
                        </div>
                        <div class="form-group col-sm-6">
                            <label>사고 지점 y좌표</label>
                            <input type="text" name="matrix2" class="form-control" maxlength="20">
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <label>교통복잡도</label>
                            <input type="text" name="matrix2" class="form-control" maxlength="20">
                        </div>
                        <!--
                            <label>교통 복잡도</label>
                            <select name="traffic" class="form-control">
                                <option value="30">많이</option>
                                <option value="10" selected>10</option>
                                <option value="0">0</option>
                            </select>
                        -->
                    </div>
                    
                    {# 푸터 #}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                        <button type="submit" class="btn btn-primary">시작</button>
                    </div>
                </form>
            </div>

        </div> 
    </div>
</div>

django/main/templates/main/tis.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Traffic Integration System</title>
    <canvas id = "ShowSimulationCanvas"></canvas>
    <canvas id = "ShowTrafficLightStateCanvas"></canvas>
    <canvas id = "ConvertTrafficLightStateCanvas"></canvas>
    <script src = "TrafficPoint.js"></script>
    <script src = "TrafficLight.js"></script>
    <script src = "TrafficCar.js"></script>
    <script src = "Canvas.js"></script>
    <script>
        function drawRect(ctx, x, y, width, height, color) {
            ctx.fillStyle = color;
            ctx.fillRect(x, y, width, height);
        }

        function drawCircle(ctx, point, color) {
            ctx.beginPath();
            ctx.arc(
                point.x, point.y, 5,
                0, Math.PI * 2,
                true
            );
            ctx.closePath();
            ctx.fillStyle = color;
            ctx.fill();
        }

        function movePoint(ctx, movePoint, rotatePoint) {
            console.log(movePoint.x, movePoint.y);

            if(movePoint.x < 200) {
                movePoint.addNowPosition(1, 0);
            } else {
                if(movePoint.y > 200) {
                    movePoint.rotatePosition(rotatePoint, -Math.PI / 24);
                } else {
                    movePoint.addNowPosition(0, -1);
                }
            }
            
            drawCircle(ctx, movePoint, "rgb(255, 0, 0)");
        }

        var point             = new TrafficPoint(0, 250);
        var rotate            = new TrafficPoint(200, 200);
        var simulationCanvas  = new Canvas("ShowSimulationCanvas", 500, 500, "rgb(255, 250, 250)", true, "rgb(100, 100, 100)");

        drawRect(simulationCanvas.canvasContext, 0, 0, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 300, 0, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 0, 300, 200, 200, "rgb(200, 200, 200)");
        drawRect(simulationCanvas.canvasContext, 300, 300, 200, 200, "rgb(200, 200, 200)");
            
        drawCircle(simulationCanvas.canvasContext, point, "rgb(255, 0, 0)");

        var init = function() {
            movePoint(simulationCanvas.canvasContext, point, rotate);
        };
        
        setInterval(
            init,
            100
        );


    </script>
</head>
<body>
</body>
</html>